### ISSUE TITLE
Version 0.4.0 Not Working on Kodi 18

### ISSUE THREAD

**Issue by joaosagrath** [aanderse/kodi-steam-library-addon#8]
Version 0.4.0

I´ve put my ID, my Web API key and set the exe location (C:\Program Files (x86)\Steam\steam.exe)

But not open the addon.

Follow the log:

https://pastebin.com/dTRU8gJ1

Using Kodi 18, Windows 7 Ultimate

Version 0.3.0 Works fine

**Comment by aanderse** [comment]
Hello,

Can you please try using the master branch instead of version 0.4.0 and let me know if that works?

Thanks,
Aaron

**Comment by joaosagrath** [comment]
Master branch working!!
